### ISSUE TITLE
Questions regarding evaluations in the paper.

### ISSUE THREAD

**Issue by aymuos15** [francescodisalvo05/medmnistc-api#1]
In Table-3, are the scores average over all the datasets within a dataset?

Example, for retinamnist, is the 70.8 AUC the average over all the following datasets?

```
.
├── brightness_down.npz
├── contrast_down.npz
├── defocus_blur.npz
├── gaussian_noise.npz
├── jpeg_compression.npz
├── motion_blur.npz
├── pixelate.npz
└── speckle_noise.npz
```

**Comment by francescodisalvo05** [comment]
Hi @aymuos15! 

Exactly, in Table 3 we averaged over all _corrupted_ datasets, as you correctly pointed out for retinamnist.
Hope it helps!

**Comment by aymuos15** [comment]
Thanks for the response! Do you by chance have a table which gives the individual scores for each for every dataset?

**Comment by francescodisalvo05** [comment]
Thank you for bringing this up! Unfortunately, due to the large number of combinations between datasets and models/augmentations, we have not yet defined specific tables, but we are considering ways to manage this!

**Comment by aymuos15** [comment]
Alright! Thank you. It is of interest to me as I plan to run some experiments (thank you very much for the open source data and code to reproduce!) so it would be helpful to have a benchmark.

**Comment by francescodisalvo05** [comment]
Absolutely, we will keep that in mind, thanks for the feedback!  💪🏻
