### ISSUE TITLE
Table 2 metrics

### ISSUE THREAD

**Issue by Drstringg** [francescodisalvo05/medmnistc-api#2]
Hi,
Thanks for your benchmark, I have problems in calculating table 2, for example I have below results for retina. How should I calculate M+: bACC and M-C: bACC

{
    "metrics": {
        "clean_score": 0.7079063409471734,
        "be": 1.0840780574200997,
        "rbe": -0.2172577898143525
    },
    "be_scores": {
        "pixelate": 1.1709787551714772,
        "jpeg_compression": 1.0268626268163716,
        "gaussian_noise": 1.1073083153798622,
        "speckle_noise": 1.2380635457738767,
        "defocus_blur": 0.9629113499867468,
        "motion_blur": 0.9380103945156416,
        "brightness_down": 1.1494467470594085,
        "contrast_down": 1.0790427246574112
    },
    "rbe_scores": {
        "pixelate": -0.07651754273316502,
        "jpeg_compression": -0.08350291581713912,
        "gaussian_noise": 0.49172257163527405,
        "speckle_noise": 0.9341694122648517,
        "defocus_blur": -0.34703421506742976,
        "motion_blur": -0.29586078306573366,
        "brightness_down": -1.3732438492765033,
        "contrast_down": -0.9877949964549751
    },
    "raw_scores": {
        "pixelate": 0.7045782990857512,
        "jpeg_compression": 0.6977761119440279,
        "gaussian_noise": 0.7796372402034277,
        "speckle_noise": 0.7595840315136548,
        "defocus_blur": 0.6627627362789192,
        "motion_blur": 0.6637137313696093,
        "brightness_down": 0.6718276156039626,
        "contrast_down": 0.6574480406855396
    }
}

**Comment by francescodisalvo05** [comment]
Hi @Drstringg , thanks for pointing this out! 

I used the notation "balanced accuracy" (instead of balanced error - BE)  to avoid confusing it with the introduced "balanced error", which requires the normalization with AlexNet results. Therefore:

"M+: bACC" refers to the balanced accuracy (without normalization) on the clean test set. Thus, you can define it as

```python
1.0 - dic["clean_score"]
```

On the other hand, "M-C: bACC" refers to the balanced accuracy (without normalization) obtained on the entire corrupted test set:

```python
1.0 - np.mean(list(dic["raw_scores"].values()))
```

Hope it helps! :D

**Comment by Drstringg** [comment]
Thank you for your response.

To be sure, in table 2 , M-C : rBE, BE , should average all dataset metrics ?

**Comment by francescodisalvo05** [comment]
Yes, in Table 2 we averaged across all datasets. However, our choice was mainly dictated by space constraints. 

For upcoming works, both individual and aggregated results may be equally interesting! 
It will mainly depend on the scope of these works.

Feel free to reach out (either here or privately) if you have more specific questions. I am happy to answer them!
